moved footer to bottom and put a border around sign in
csumb-serious-business/personalized-storytime-stories pull request #7
Opened 2020-04-14 02:01 UTC by jkasato

moved footer to bottom and put a border around sign in

2020-04-14 02:58 UTC, mrobertson-csumb requested changes
The files in the bin directory should not have been added

2020-04-14 03:51 UTC, jkasato commented
> The files in the bin directory should not have been added

How do I removed those changes and only include the css file that I added?

2020-04-15 06:18 UTC, mrobertson-csumb commented on .gitignore
> +!**/bin/**
this line as written is an unignore. it should simply be:
bin/

2020-04-15 06:29 UTC, mrobertson-csumb requested changes
Needs minor changes.
See inline comments.

2020-04-15 06:29 UTC, mrobertson-csumb commented on src/main/resources/public/css/styles.css
> +	padding:0;
use a code formatter on the file before committing

2020-04-15 06:29 UTC, mrobertson-csumb commented on src/main/resources/public/css/styles.css
> +  	height: 3 rem; /* Footer height */
no space between scalar and unit

2020-04-15 06:29 UTC, mrobertson-csumb commented on src/main/resources/public/css/styles.css
> +#footer-id {
footer is unreadably small when rendered on the page.
footer is not anchored at the very bottom of the page, there is a gap about 1.5x the height of the footer.

2020-04-17 02:18 UTC, mrobertson-csumb requested changes

2020-04-17 02:18 UTC, mrobertson-csumb commented on src/main/resources/public/css/styles.css
> +	width: 100%;
width already defined above.

2020-04-17 02:18 UTC, mrobertson-csumb commented on src/main/resources/public/css/styles.css
> +	font-size: 0.6em;
0.8em is the smallest that looks OK on my browser.

2020-04-17 05:56 UTC, mrobertson-csumb approved these changes

2020-04-17 05:57 UTC, merged